#!/usr/bin/env perl
# vim: softtabstop=2 shiftwidth=2 expandtab

print "---------- SETTING UP ----------\n";
use feature 'say';
use strict;
use warnings;
use YAML::XS 'LoadFile';
use File::Find;

# Presets
my $KeyDir = "/etc/efi-keys";
my $DeleteUnsigned = "0";
my $SignBackup = "1";
    
my $config = LoadFile('/etc/zfsbootmenu/config.yaml');

my $Global = $config->{Global};
my $ESP = $Global->{BootMountPoint};
my $ZBM = "$ESP/EFI/zbm";
my $SecureBoot = $config->{SecureBoot};
my @EFIBins;

if ($SecureBoot) {
    $KeyDir = $SecureBoot->{KeyDir};
    $DeleteUnsigned = $SecureBoot->{DeleteUnsigned};
    $SignBackup = $SecureBoot->{SignBackup};
}

opendir my $ZBM_dir, $ZBM
    or die "Cannot open ZBM dir: $ZBM";

if ($SignBackup) {
    @EFIBins = grep { !/signed\.efi$/i and /\.efi/i } readdir $ZBM_dir;
}
else {
    @EFIBins = grep { !/signed\.efi$/i and !/backup/i and /\.efi/i } readdir $ZBM_dir;
}

say "Found: @EFIBins";

for(@EFIBins){
    my $Unsigned = substr($_,0,-4);
    say "Signing $Unsigned";
    system "sbsign --key $KeyDir/DB.key --cert $KeyDir/DB.crt $ZBM/$_ --output $ZBM/$Unsigned-signed.efi";
    if ($DeleteUnsigned) {
        say "Deleting unsigned $_";
        system "rm $ZBM/$_";
    }
}
print "---------- FINISHED ----------\n";
